### ISSUE TITLE
Output warning if using skcosmo without the proper sklearn version

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/scikit-matter#115]
Hello, I had problems with skcosmo due to an older (but not very old) sklearn version. We should return a warning if the used sklearn version is not 0.24.2 and also mention this in the README, because otherwise it is nearly impossible to find out.

**Comment by rosecers** [comment]
course of action: require 1.0 and send warning when not present

**Comment by agoscinski** [comment]
Because of test failures due to old scikit-learn version in #140 (The datasets have changed with the 1.1.0 version). We dropped support for anything below scikit-learn 1.1.0 and put it this in the setup.cfg `install_requires`
