### ISSUE TITLE
Create a CONDA forge recipe 

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/scikit-matter#173]
Many people do not use pip but only conda. Since the paper will come out at some point we should make it for new users as convenient as possible. Putting a pure Python package on anaconda with conda-forge is fairly easy. If we want to do this I can also take care of this.

**Comment by Luthaf** [comment]
I'm already familiar with conda-forge, so you can also put me as a maintainer in the recipe.

**Comment by PicoCentauri** [comment]
See https://github.com/conda-forge/staged-recipes/pull/22399 for the status on the recipe.

**Comment by PicoCentauri** [comment]
sckit-matter is now available on conda: https://anaconda.org/conda-forge/skmatter

🥳
