### ISSUE TITLE
PCovR-WHODataset takes super long to compute

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/scikit-matter#175]
The example suit of scikit-matter is super nice and well structured. Most of them run also fast, but while I was working on #170 on found that the `PCovR-WHODataset` examples take ages to compute.

It might be worth revising the example to speed this up. An example that takes several minutes for execution is not very useful. If there is no way to speed this up we at least should add a note.

**Comment by rosecers** [comment]
Addressed in #189
