### ISSUE TITLE
WHO dataset missing function call section in doc

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/scikit-matter#181]
load_csd_1000r has the section https://scikit-matter.readthedocs.io/en/latest/datasets.html#skmatter.datasets.load_csd_1000r but not the who dataset https://scikit-matter.readthedocs.io/en/latest/datasets.html#who-dataset

Also I would try to change this to `autofunction`, not sure if this results in problems since the descriptions are in the code folder
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autofunction

**Comment by rosecers** [comment]
Addressed in #192
